### PR TITLE
Set correct types when creating PaymentSource

### PR DESCRIPTION
**Pull request by leevigraham**
### Related issues

https://github.com/craftcms/commerce-stripe/issues/201

### CODE REVIEW

**Comment by lukeholder** [comment]
Thanks!

**Comment by lukeholder** [comment]
@nfourtythree Can you update the changelog too please.

**Comment by leevigraham** [comment]
> Reverted this as it was merged into 2.x when it was meant to be 3.x

Whoops… I though develop was the 3.x branch now. Apologies.

**Comment by leevigraham** [comment]
Created a new PR: https://github.com/craftcms/commerce-stripe/pull/204

**Pull request merged**
